// Generated by Wrangler on Tue Aug 13 2024 20:03:18 GMT+0200 (Central European Summer Time)
// by running `wrangler types`

interface Env {
	MY_DURABLE_OBJECT: DurableObjectNamespace /* MyDurableObject */;
	COUNTERS: DurableObjectNamespace /* Counter */;
}
